version: 2
jobs:
 build_linux:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t arnislielturks/urho3d:$CIRCLE_BUILD_NUM-linux -f Dockerfile-Linux .
     - run: docker push arnislielturks/urho3d:$CIRCLE_BUILD_NUM-linux
 build_windows:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t arnislielturks/urho3d:$CIRCLE_BUILD_NUM-windows -f Dockerfile-Windows .
     - run: docker push arnislielturks/urho3d:$CIRCLE_BUILD_NUM-windows
workflows:
  version: 2
  build:
    jobs:
    - build_linux
    - build_windows
