version: 2
jobs:
 build_complete:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t arnislielturks/urho3d:$CIRCLE_BUILD_NUM .
     - run: docker push arnislielturks/urho3d:$CIRCLE_BUILD_NUM
 build_no_scripts:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t arnislielturks/urho3d:$CIRCLE_BUILD_NUM-no-scripts -f Dockerfile-no-scripting .
     - run: docker push arnislielturks/urho3d:$CIRCLE_BUILD_NUM-no-scripts
workflows:
  version: 2
  build:
    jobs:
    - build_complete
    - build_no_scripts
